USER/urls.py
from django.urls import path
from .views import (Sign_up,
                    Sign_in,
                    research_details,
                    res_help_details,
                    web_details,
                    video_details,
                    thesis_details,
                    transcription_details,
                    wr_ed_details,
                    business_details,
                    graphics_details,
                    programming_details,
                    assignment_details,
                    contact_us,
                    terms_and_condition,
                    privacy_policy,
                    submit_review,
                    )

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'user'

urlpatterns = [
    path('privacy_policy/',privacy_policy,name='privacy_policy'),
    path('terms_and_conditions/',terms_and_condition,name='terms_and_conditions'),

    path('submit_review/', submit_review, name='submit_review'),
    # path('thank_you/', thank_you, name='thank_you'),


    path('login/',Sign_in,name='login' ),
    path('signup/', Sign_up, name='signup'),
    # path('dashboard/', home, name='home_page'),
    path('web_details/', web_details, name='web-details'),
    path('res_details/', research_details, name='research-details'),
    path('rh_details/', res_help_details, name='res_help-details'),
    path('video_details/', video_details, name='video-details'),
    path('the_details/', thesis_details, name='thesis-details'),
    path('tran_details/', transcription_details, name='transcription-details'),
    path('ass_details/', assignment_details, name='assignment-details'),
    path('graph_details/', graphics_details, name='graphics-details'),
    path('wd_details/', wr_ed_details, name='wr-ed-details'),
    path('bus_details/', business_details, name='business-details'),
    path('pro_details/', programming_details, name='programming-details'),


    path('contactus/', contact_us, name='contactus'),
    path('logout/',LogoutView.as_view(),name='logout'),

    
    path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html',email_template_name='user/password_reset_email.html',success_url = reverse_lazy('user:password_reset_done')),name='password-reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm1/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm1.html',success_url = reverse_lazy('user:password_reset_complete')),name='password_reset_confirm'),
    path('password-reset-complete1/done',PasswordResetCompleteView.as_view(template_name='user/password_reset_complete1.html'),name='password_reset_complete'),
    

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_page
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page,name='base1'),
    path('', include(('USER.urls','USER') ,'user1')),
    # path('', include(('HOME.urls','HOME') ,'home')),
    path('', include(('ORDER.urls','ORDER') ,'order')),
    path('', include(('chat.urls','chat') ,'chat')),


]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

USER/models.py
from django.db import models

class Contact_us_page(models.Model):
    name = models.CharField(null=False,max_length=50)
    email = models.EmailField(null=False, blank=False)
    Subject = models.TextField(null=False, blank=False)
    message = models.TextField(null=False, blank=False)
    # date = models.DateTimeField(auto_created=True, blank=False)
    
    def __str__(self):
        return self.name
    
class Review(models.Model):
    RATINGS = [
        (1, '1 Star'),
        (2, '2 Stars'),
        (3, '3 Stars'),
        (4, '4 Stars'),
        (5, '5 Stars'),
    ]

    name = models.CharField(max_length=100)
    email = models.EmailField()
    rating = models.PositiveIntegerField(choices=RATINGS)
    comments = models.TextField()

    def __str__(self):
        return f'{self.name} - {self.rating} Stars'

USER/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth import login,logout as aut_logout,authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.validators import validate_email
from .form import Contact_form
from .models import Review
from django.urls import reverse_lazy
# from django.views.decorators.csrf import csrf_exempt
# from django.views.decorators.http import require_POST
# import time
# Create your views here.
def Sign_in(request):
    if request.method == 'POST':
        username_or_email = request.POST.get('username')
        password = request.POST.get('password')
        

        # Check if the input is an email address
        if '@' in username_or_email:
            # If it's an email address, try to get the user with that email
            try:
                user = User.objects.get(email=username_or_email)
            except User.DoesNotExist:
                user = None
        else:
            # If it's not an email address, try to get the user with that username
            user = User.objects.filter(username=username_or_email).first()

        if user is None:
            # Display an error message if the user does not exist
            messages.error(request, 'Invalid username or email')
            return redirect(reverse_lazy('user:login'))

        # Authenticate the user with the provided username/email and password
        authenticated_user = authenticate(request, username=user.username, password=password)

        if authenticated_user is None:
            # Display an error message if authentication fails (invalid password)
            print(username_or_email,password)
            messages.error(request, "Invalid password")
            return redirect(reverse_lazy('user:login'))
        else:
            # Log in the user and redirect to the home page upon successful login
            login(request, authenticated_user)
            if 'next' in request.POST:
                next = request.POST.get('next').strip('/')
                try:
                    return redirect(reverse_lazy('user:'+ next))
                
                except:
                    return redirect(reverse_lazy('order:'+ next))
            return redirect(reverse_lazy('order:profile'))
    return render (request,'user/login.html')

def Sign_up(request):

    if request.method=='POST':
        uname=request.POST.get('username')
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')
        if pass1==pass2:
            user = User.objects.filter(username=uname)
            
            if user.exists():
                # Display an information message if the username is taken
                messages.error(request, "Username already taken!")
                return redirect(reverse_lazy('user:signup'))
            if len(pass1) <8:
            # Display an error message if password less than 8
                messages.error(request, "password is too short please use strong password")
                return redirect(reverse_lazy('user:signup'))
            if validate_email(email):
                messages.error(request, "invalid email")
                return redirect(reverse_lazy('user:signup'))
            
            # Create a new User object with the provided information
            user = User.objects.create_user(
                username=uname,
                email=email
            )
            
            # Set the user's password and save the user object
            user.set_password(pass1)
            user.save()
        
            # Display an information message indicating successful account creation
            messages.success(request, "Account created Successfully! please login")
            return redirect(reverse_lazy('user:login'))
        else:
            messages.error(request,'please make sure you confirm the password correctly')
            return redirect(reverse_lazy('user:signup'))
    return render (request,'user/register.html')



def web_details(request):
    return render(request,'ditails/webdevelopement.html')

def research_details(request):
    return render(request,'ditails/research.html')

def thesis_details(request):
    return render(request,'ditails/thesis.html')

def graphics_details(request):
    return render(request,'ditails/graphics.html')

def business_details(request):
    return render(request,'ditails/business.html')

def assignment_details(request):
    return render(request,'ditails/assignment.html')

def transcription_details(request):
    return render(request,'ditails/transcription.html')

def video_details(request):
    return render(request,'ditails/video.html')

def res_help_details(request):
    return render(request,'ditails/researchhelp.html')

def programming_details(request):
    return render(request,'ditails/programming.html')

def wr_ed_details(request):
    return render(request,'ditails/writingediting.html')

def contact_us(request):

    form = Contact_form()
    if request.method == 'POST':
        form = Contact_form(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'your information has been sent we will contact you soon')
            return redirect('/#contact')

        else:messages.error(request,'please enter the correct information')
        return redirect('/#contact')
        
    else:
        form = Contact_form()
        
def logout_page(request):
    if request.method == 'POST':
        aut_logout(request)
    return redirect(reverse_lazy('base1'))

def terms_and_condition(request):
    return render(request, 'terms_and_conditions.html')

def privacy_policy(request):
    return render(request, 'privacy_policy.html')

def submit_review(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        rating = request.POST.get('rating')
        comment = request.POST.get('comments')

        if name and email and rating and comment:
            Review.objects.create(name=name, email=email, rating=rating, comments=comment)
            messages.success(request,'tank you for your review')
            return redirect(reverse_lazy('user:submit_review'))

        else:
            messages.error(request,'please check you fill ditails correctly and fill the stars')
            return redirect(reverse_lazy('user:submit_review'))
    
    return render(request, 'submit_review.html')

USER/templates/user/login.html
{%extends 'base.html'%} {% load static %}
<title>{% block title %}login {%endblock%} | assignment helper</title>


{%block content%}

<main class="main">
  <!-- Page Title -->
  <div class="page-title">
    <div class="heading">
      <div class="container">
        <div class="row d-flex justify-content-center text-center">
          <div class="col-lg-8">
            <h1>Service Details</h1>
            <p class="mb-0">
              Whether you're seeking academic support, business solutions, or creative assistance, our team of experts is dedicated to providing exceptional quality and results. From in-depth research and comprehensive thesis writing to professional web development and innovative graphic design, UNION is your trusted partner in success. Explore our range of services and discover how we can help you achieve your goals with excellence and efficiency.
            </p>
          </div>
        </div>
      </div>
    </div>
    <nav class="breadcrumbs">
      <div class="container">
        <ol>
          <li><a href="{%url 'base1'%}">Home</a></li>
          <li class="current">login</li>
        </ol>
      </div>
    </nav>
  </div>
  <!-- End Page Title -->

  <!-- Service Details Section -->
  <section id="service-details" class="service-details-section">
    <form class="login-form" method="post">
      <h3 class="form-title">Login Here</h3>
      {% csrf_token %}
      {% if messages %}
        <ul class="messages" id="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
      {% endif %}
      <label for="username" class="form-label">Username</label>
      <input type="text" placeholder="Enter Username" id="username" name="username" class="form-input" />

      <label for="password" class="form-label">Password</label>
      <input type="password" placeholder="Password" id="password" name="password" class="form-input" />
      {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}" />
      {% endif %}
      <button type="submit" class="submit-button">Log In</button>
      <a href="{% url 'user:signup' %}" class="form-link">Create an account</a>
      <a href="{% url 'user:password-reset' %}" class="form-link">Forgot password</a>
    </form>
  </section>
</main>

{%endblock%}

USER/templates/user/password_reset.html
{% extends 'base.html' %}{%load static%}

<title>{% block title %}
  password-reset
{% endblock %}</title>



{% block content %}
<section>
  <div class="center">
    <form method="post" class="new_card">
      {% csrf_token %}
      <h2 class="text-center">Reset Password</h2>
      {% for field in form %}
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
          <small>{{ field.errors|striptags }}</small>
        {% endif %}
      {% endfor %}
      <div class="form-buttons">
        <input type="submit" value="Send" class="btn btn-primary" />
        <a class="cancel" href="{%url 'user:login'%}">Cancel</a>
      </div>
    </form>
  </div>
</section>
{% endblock %}

USER/templates/user/password_reset_complete1.html
{%extends 'base.html'%} 
{%block content%}
<section>

  <div class="card center">
    <p>
      Your password has been changed successfully. Please
      <a href="{% url 'user:login' %}">Login</a>
    </p>
  </div>
</section>


{%endblock content%}

USER/templates/user/password_reset_confirm1.html
{% extends 'base.html' %}{% load static %}

{% block title %}Confirm{% endblock %}

  
{% block content %}
<section>
{% if validlink %}
  <h1>Set a new password!</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change my password">
  </form>
{% else %}
  <p>The password reset link is no longer valid. Please request a new one.</p>
{% endif %}
</section>
{% endblock %}

USER/templates/user/password_reset_done.html
{%extends 'base.html'%}
<title>{%block title%} done {%endblock%}</title>

{%block content%}
<section class="prdone">
<div class="center-card">
	<h2>Check Your email</h2>
	<p>Please check your inbox if you don't get the link please check it in spam folder and follow the instruction to reset your password.</p>
</div>
</section>
{%endblock%}

USER/templates/user/password_reset_email.html
{% autoescape off %}
Hi,

Please click the link below to reset your password:

{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

If you didn’t request this, you can ignore this email.

Thanks,  
The UNION team
{% endautoescape %}

USER/templates/user/register.html
{%extends 'base1.html'%} {% load static %}
<title>{% block title %} signup {%endblock%} | assignment helper</title>

{% block content %}
<!-- <div class="background">
  <div class="shape"></div>
  <div class="shape"></div>
</div> -->

<main class="main">
  <!-- Page Title -->
  <div class="page-title">
    <div class="heading">
      <div class="container">
        <div class="row d-flex justify-content-center text-center">
          <div class="col-lg-8">
            <h1>Service Details</h1>
            <p class="mb-0">
              Whether you're seeking academic support, business solutions, or creative assistance, our team of experts is dedicated to providing exceptional quality and results. From in-depth research and comprehensive thesis writing to professional web development and innovative graphic design, UNION is your trusted partner in success. Explore our range of services and discover how we can help you achieve your goals with excellence and efficiency.
            </p>
          </div>
        </div>
      </div>
    </div>
    <nav class="breadcrumbs">
      <div class="container">
        <ol>
          <li><a href="{%url 'base1'%}">Home</a></li>
          <li class="current">signup</li>
        </ol>
      </div>
    </nav>
  </div>
  <!-- End Page Title -->

  <!-- Service Details Section -->
  <section id="service-details" class="service-details section">
    <form action="{%url 'user:signup'%}" method="post" class="signup-form">
      {% csrf_token %}
      <h3 class="form-title">Signup Here</h3>
      {% if messages %}
        <ul class="messages" id="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
      {% endif %}

      <label for="username" class="form-label">Username</label>
      <input
        type="text"
        placeholder="Username"
        name="username"
        id="username"
        required
        class="form-input"
      />

      <label for="email" class="form-label">Email</label>
      <input
        type="email"
        placeholder="Email or Phone"
        name="email"
        id="email"
        required
        class="form-input"
      />

      <label for="password1" class="form-label">Password</label>
      <input
        type="password"
        placeholder="Password"
        id="password1"
        name="password1"
        required
        class="form-input"
      />

      <label for="password2" class="form-label">Confirm Password</label>
      <input
        type="password"
        placeholder="Confirm Password"
        id="password2"
        name="password2"
        required
        class="form-input"
      />
      <button type="submit" class="submit-button">Signup</button>

      <a href="{% url 'user:login' %}" class="form-link">I have an account</a>
    </form>
  </section>
  <!-- /Service Details Section -->
</main>

{%endblock%}