ORDER/urls.py
from django.urls import path
from .views import (profile_page,research_help,Writing_editing_project,create_research,create_thesis,graphics_design_submission,programming_project_submission,video_editing_submission,transcription,business_plan,assignment,user_orders,completed_orders,pending_orders,website_project)
from django.conf import settings
from django.conf.urls.static import static


app_name = 'order'

urlpatterns = [
               
    path('pending_orders/',pending_orders,name='pending_orders' ),
    path('completed_orders/',completed_orders,name='completed_orders' ),
    path('total_order/',user_orders,name='total_order' ),
    
    path('order/',create_research,name='order' ),
    path('thesis/',create_thesis,name='thesis' ),
    path('graphdesign/',graphics_design_submission,name='graphics-design' ),
    path('programming/',programming_project_submission,name='program-project' ),
    path('video/',video_editing_submission,name='video-project' ),
    path('transcription/',transcription,name='transcription' ),
    path('assignment/',assignment,name='assignment' ),
    path('business/',business_plan,name='business-plan' ),
    path('website/',website_project,name='website-project' ),
    path('editing/',Writing_editing_project,name='editing-project' ),
    path('research_help/',research_help,name='research_help'),

    path('profile/',profile_page,name='profile' ),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

USER/urls.py
from django.urls import path
from .views import (Sign_up,
                    Sign_in,
                    research_details,
                    res_help_details,
                    web_details,
                    video_details,
                    thesis_details,
                    transcription_details,
                    wr_ed_details,
                    business_details,
                    graphics_details,
                    programming_details,
                    assignment_details,
                    contact_us,
                    terms_and_condition,
                    privacy_policy,
                    submit_review,
                    )

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'user'

urlpatterns = [
    path('privacy_policy/',privacy_policy,name='privacy_policy'),
    path('terms_and_conditions/',terms_and_condition,name='terms_and_conditions'),

    path('submit_review/', submit_review, name='submit_review'),
    # path('thank_you/', thank_you, name='thank_you'),


    path('login/',Sign_in,name='login' ),
    path('signup/', Sign_up, name='signup'),
    # path('dashboard/', home, name='home_page'),
    path('web_details/', web_details, name='web-details'),
    path('res_details/', research_details, name='research-details'),
    path('rh_details/', res_help_details, name='res_help-details'),
    path('video_details/', video_details, name='video-details'),
    path('the_details/', thesis_details, name='thesis-details'),
    path('tran_details/', transcription_details, name='transcription-details'),
    path('ass_details/', assignment_details, name='assignment-details'),
    path('graph_details/', graphics_details, name='graphics-details'),
    path('wd_details/', wr_ed_details, name='wr-ed-details'),
    path('bus_details/', business_details, name='business-details'),
    path('pro_details/', programming_details, name='programming-details'),


    path('contactus/', contact_us, name='contactus'),
    path('logout/',LogoutView.as_view(),name='logout'),

    
    path('password-reset/', PasswordResetView.as_view(template_name='user/password_reset.html',email_template_name='user/password_reset_email.html',success_url = reverse_lazy('user:password_reset_done')),name='password-reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm1/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm1.html',success_url = reverse_lazy('user:password_reset_complete')),name='password_reset_confirm'),
    path('password-reset-complete1/done',PasswordResetCompleteView.as_view(template_name='user/password_reset_complete1.html'),name='password_reset_complete'),
    

]

chat/urls.py
from django.urls import path
from .views import load_previous_chats, check_unread_messages,send_message

app_name = 'chat'

urlpatterns = [
    # path('chat/',chat_view,name='chat' ),

# urls.py
    path('send-message/',send_message, name='send_message'),

    path('load-previous-chats/', load_previous_chats, name='load_previous_chats'),
    path('check-unread-messages/', check_unread_messages, name='check_unread_messages'),
    # other paths
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_page
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page,name='base1'),
    path('', include(('USER.urls','USER') ,'user1')),
    # path('', include(('HOME.urls','HOME') ,'home')),
    path('', include(('ORDER.urls','ORDER') ,'order')),
    path('', include(('chat.urls','chat') ,'chat')),


]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ORDER/forms.py
# from django import forms
# from .models import Order,Order2

# class Order_form(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ['resume_type', 'deadline','price_quote']
# class Order_form2(forms.ModelForm):
#     class Meta:
#         model = Order2
#         fields = [
#             'firstname', 'lastname', 'email', 'phone_number', 'gender',
#             'title', 'number_of_pages', 'deadline', 'abstract',
#             'description', 'accept_terms'
#         ]
#         widgets = {
#             'firstname': forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control'}),
#             'lastname': forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}),
#             'email': forms.EmailInput(attrs={'placeholder': 'Your Email', 'class': 'form-control'}),
#             'phone_number': forms.TextInput(attrs={'placeholder': 'Phone Number', 'class': 'form-control'}),
#             'gender': forms.RadioSelect,
#             'title': forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}),
#             'number_of_pages': forms.NumberInput(attrs={'placeholder': 'Number of Pages', 'class': 'form-control'}),
#             'deadline': forms.DateInput(attrs={'placeholder': 'Deadline', 'class': 'form-control'}),
#             'abstract': forms.ClearableFileInput(attrs={'placeholder': 'Abstract', 'class': 'form-control'}),
#             'description': forms.Textarea(attrs={'placeholder': 'Your message here!', 'class': 'form-control', 'style': 'height: 99px;'}),
#             'accept_terms': forms.CheckboxInput(attrs={'class': 'form-control'})
#         }

ORDER/views.py
from django.shortcuts import render,redirect
from .models import (editing,Website_project,Research,Thesis,Research_help,GraphicsDesignSubmission,ProgrammingProjectSubmission,VideoEditingSubmission,Transcription,Assignment,Business_plan)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy

# Create your views here.
def utility(user):
    graphics = GraphicsDesignSubmission.objects.filter(user_name=user,status='completed').count()
    programming = ProgrammingProjectSubmission.objects.filter(user_name=user,status='completed').count()
    video = VideoEditingSubmission.objects.filter(user_name=user,status='completed').count()
    transcription = Transcription.objects.filter(user_name=user,status='completed').count()
    assignment = Assignment.objects.filter(user_name=user,status='completed').count()
    business_plans = Business_plan.objects.filter(user_name=user,status='completed').count()
    researches = Research.objects.filter(user_name=user,status='completed').count()
    theses = Thesis.objects.filter(user_name=user,status='completed').count()
    website = Website_project.objects.filter(user_name=user,status='completed').count()
    edit = editing.objects.filter(user_name=user,status='completed').count()
    research_help = Research_help.objects.filter(user_name=user,status='completed').count()

    total_completed_orders = research_help + graphics + programming + video + assignment + business_plans + researches + theses  + transcription + website + edit

    tgraphics = GraphicsDesignSubmission.objects.filter(user_name=user,status='pending').count()
    tprogramming = ProgrammingProjectSubmission.objects.filter(user_name=user,status='pending').count()
    tvideo = VideoEditingSubmission.objects.filter(user_name=user,status='pending').count()
    ttranscription = Transcription.objects.filter(user_name=user,status='pending').count()
    tassignment = Assignment.objects.filter(user_name=user,status='pending').count()
    tbusiness_plans = Business_plan.objects.filter(user_name=user,status='pending').count()
    tresearches = Research.objects.filter(user_name=user,status='pending').count()
    ttheses = Thesis.objects.filter(user_name=user,status='pending').count()
    twebsite = Website_project.objects.filter(user_name=user,status='pending').count()
    tedit = editing.objects.filter(user_name=user,status='pending').count()
    treserch_help = Research_help.objects.filter(user_name=user,status='pending').count()

    total_pending_orders = treserch_help + tgraphics + tprogramming + tvideo + tassignment + tbusiness_plans + tresearches + ttheses  + ttranscription + twebsite + tedit

    total = total_pending_orders + total_completed_orders 
    
    return total,total_pending_orders,total_completed_orders

@login_required(login_url='user:login')
def profile_page(request):
    total,pending,completed = utility(request.user)
    context = {
        'total_completed':completed,
        'total_pending':pending,
        'total':total,

    }
    return render(request,'order/profile.html',context)


@login_required
def user_orders(request):
    # Retrieve orders for the logged-in user
    graphics = GraphicsDesignSubmission.objects.filter(user_name=request.user)
    programming = ProgrammingProjectSubmission.objects.filter(user_name=request.user)
    video = VideoEditingSubmission.objects.filter(user_name=request.user)
    transcription = Transcription.objects.filter(user_name=request.user)
    assignment = Assignment.objects.filter(user_name=request.user)
    business_plans = Business_plan.objects.filter(user_name=request.user)
    researches = Research.objects.filter(user_name=request.user)
    theses = Thesis.objects.filter(user_name=request.user)
    web = Website_project.objects.filter(user_name=request.user)
    edit = editing.objects.filter(user_name=request.user)
    research_help = Research_help.objects.filter(user_name=request.user)
    
    total,pending,completed = utility(request.user)

    context = {
        'total_completed':completed,
        'total_pending':pending,
        'total':total,
        'business_plans': business_plans,
        'researches': researches,
        'theses': theses,
        'assignment':assignment,
        'transcriptions':transcription,
        'videos':video,
        'programmings':programming,
        'graphicss':graphics,
        'websites':web,
        'editings':edit,
        'research_help': research_help
    }

    return render(request, 'order/ordres.html', context)

@login_required(login_url='user:login')
def completed_orders(request):
    # Retrieve orders for the logged-in user
    graphics = GraphicsDesignSubmission.objects.filter(user_name=request.user,status='completed')
    programming = ProgrammingProjectSubmission.objects.filter(user_name=request.user,status='completed')
    video = VideoEditingSubmission.objects.filter(user_name=request.user,status='completed')
    transcription = Transcription.objects.filter(user_name=request.user,status='completed')
    assignment = Assignment.objects.filter(user_name=request.user,status='completed')
    business_plans = Business_plan.objects.filter(user_name=request.user,status='completed')
    researches = Research.objects.filter(user_name=request.user,status='completed')
    theses = Thesis.objects.filter(user_name=request.user,status='completed')
    web = Website_project.objects.filter(user_name=request.user,status='completed')
    edit = editing.objects.filter(user_name=request.user,status='completed')
    research_help = Research_help.objects.filter(user_name=request.user,status='completed')

    total,pending,completed = utility(request.user)

    context = {
        'total_completed':completed,
        'total_pending':pending,
        'total':total,
        'business_plans': business_plans,
        'researches': researches,
        'theses': theses,
        'assignment':assignment,
        'transcriptions':transcription,
        'videos':video,
        'programmings':programming,
        'graphicss':graphics,
        'websites':web,
        'editings':edit,
        'research_help': research_help
    }

    return render(request, 'order/completed_ordres.html', context)

@login_required(login_url='user:login')
def pending_orders(request):
    # Retrieve orders for the logged-in user
    graphics = GraphicsDesignSubmission.objects.filter(user_name=request.user,status='pending')
    programming = ProgrammingProjectSubmission.objects.filter(user_name=request.user,status='pending')
    video = VideoEditingSubmission.objects.filter(user_name=request.user,status='pending')
    transcription = Transcription.objects.filter(user_name=request.user,status='pending')
    assignment = Assignment.objects.filter(user_name=request.user,status='pending')
    business_plans = Business_plan.objects.filter(user_name=request.user,status='pending')
    researches = Research.objects.filter(user_name=request.user,status='pending')
    theses = Thesis.objects.filter(user_name=request.user,status='pending')
    web = Website_project.objects.filter(user_name=request.user,status='pending')
    edit = editing.objects.filter(user_name=request.user,status='pending')
    total,pending,completed = utility(request.user)

    context = {
        'total_completed':completed,
        'total_pending':pending,
        'total':total,
        'business_plans': business_plans,
        'researches': researches,
        'theses': theses,
        'assignment':assignment,
        'transcriptions':transcription,
        'videos':video,
        'programmings':programming,
        'graphicss':graphics,
        'websites':web,
        'editings':edit
    }

    return render(request, 'order/pending_ordres.html', context)



@login_required(login_url='user:login')
def create_research(request):
    if request.method == 'POST':
        user_name = request.user
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        gender = request.POST.get('gender')
        titles = request.POST.get('title')
        number_of_pages = request.POST.get('number_of_pages')
        abstract = request.FILES.get('abstract')
        description = request.POST.get('description')
        accept_terms = request.POST.get('accept_terms')== 'on'

        if user_name and firstname and lastname and email and phone_number and gender and titles and number_of_pages and abstract and description and accept_terms:
            Research.objects.create(user_name=user_name, firstname=firstname, lastname=lastname,email=email,phone_number=phone_number,gender=gender,title=titles,number_of_pages=number_of_pages,abstract=abstract,description=description,accept_terms=accept_terms)
            messages.success(request,'order submitted successfully you can see it in the dashboard ')
            
            return redirect(reverse_lazy('order:order'))
        else:
            messages.error(request,'please check the form again and check every thing is filled correctly!')
            return redirect(reverse_lazy('order:order'))
        # Replace with your success URL

    return render(request, 'order/research.html')


@login_required(login_url='user:login')
def research_help(request):
    if request.method == 'POST':
        user_name = request.user
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        gender = request.POST.get('gender')
        titles = request.POST.get('title')
        number_of_pages = request.POST.get('number_of_pages')
        abstract = request.FILES.get('abstract')
        description = request.POST.get('description')
        accept_terms = request.POST.get('accept_terms')== 'on'

ORDER/templates/order/profile.html
{% extends 'base.html' %}{%load static%}
{% load active_url %}

<!-- partial:index.partial.html -->
<title>{% block title %} Profile {%endblock%}</title>

{% block content %}
<section id="profile">
  <div id="message-icon">
    <i class="fa fa-envelope"></i>
    <span class="badge">0</span>
</div>

<form method="POST" action="{%url 'chat:send_message'%}">
  {%csrf_token%}
<div id="chat-panel">
    <div id="chat-header">
        Send Message
        <span class="close-btn">&times;</span>
    </div>
    <div id="chat-body">
        <!-- Previous chats will be loaded here -->
    </div>
    <div id="chat-footer">
        <input name="content" type="text" id="chat-input" placeholder="Type a message">
        <button type="submit" id="send-btn">Send</button>
    </div>
    
</div>
</form>
    <div id="cols__container1" class="cols__container">
      <div class="left__col">
              <div class="img__container">
    <img src="{% static 'css/image.png' %}" alt="photo">
      <span></span>
    </div>
    
    <h2>{{request.user.username}}</h2>
    <p>{{request.user.email}}</p>
    <p>welcome to UNION</p>

    <ul class="profile_about">
      <li><span>{{total}}</span>ordered services</li>
              <li><span>{{total_completed}}</span>completed</li>
              <li><span>{{total_pending}}</span>ongoing</li>
    </ul>
    
    
    <div class="content">
      <p>Ready to elevate your projects to the next level? Our expert team is here to provide top-notch assistance tailored to your needs. Don't wait any longer—place your order today and experience exceptional service and results!. </p>
    </div>
    </div>
    <div class="right__col">
      <nav class="uls">
           <ul >
            <li><a class="{% is_active request 'order:profile' %}" href="{%url 'order:profile'%}">how to Order</a></li>
            <li><a class="{% is_active request 'order:total_order' %}" href="{%url 'order:total_order'%}">Ordered</></li>
             <li><a class="{% is_active request 'order:completed_orders' %}" href="{%url 'order:completed_orders'%}">Completed</a></li>
             <li><a class="{% is_active request 'order:pending_orders' %}" href="{%url 'order:pending_orders'%}">Ongoing</a></li>
      </ul>
      <!-- <a href="#services"><button>Get in touch</button></a> -->
      <a href="#services"><button>Order Now</button></a>
        
      </nav>
      
      <div>
        {% block content2 %}
    
        <ol>
          <li><strong>Click the "Order Now" button or scroll down to choose your order.</strong></li> <br>
          <li><strong>Once you choose your order and fill out the form correctly with the correct information, submit it. You will then see your order on the "Ordered" page.</strong></li> <br>
          <li><strong>After you submit your order, we will call you or email you for more details. Please answer the call or check your email.</strong></li> <br>
          <li><strong>If you face any trouble, please leave your message in the message box shown at the bottom of the page. Through it, you will directly talk to the admin, and you can even change or delete your orders.</strong></li> <br>
      </ol>

        <div style="text-align: center; margin-top: 20px;">
          <a href="https://www.example.com/video-link" target="_blank" class="btn" style="background-color: #008374; color: white;">More</a>
      </div>
    
        {% endblock %}
    </div>
    
    </div>
    
  </section>
  <!-- Services Section -->
  <section id="services" class="services section">
  
    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Order Services</h2>
      <p>At UNION, we offer a comprehensive range of services to support students in their academic and professional journeys. Our goal is to provide high-quality assistance tailored to your needs. Our services include:</p>
    </div><!-- End Section Title -->
  
    <div class="container">
  
      <div class="row gy-4">
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-activity"></i>
            </div>
            <h3>Research</h3>
            <p>Thorough and detailed research services for your academic projects and papers.</p>
            <a href="{% url 'order:order'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="200">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-broadcast"></i>
            </div>
            <h3>Thesis Support</h3>
            <p>Comprehensive support through the second phase of your thesis development.</p>
            <a href="{% url 'order:thesis'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="300">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-easel"></i>
            </div>
            <h3>Business Plan Writing</h3>
            <p>Expert assistance in crafting professional business plans.</p>
            <a href="{% url 'order:business-plan'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="400">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-bounding-box-circles"></i>
            </div>
            <h3>Assignment Help</h3>
            <p>Reliable help with your assignments to ensure high-quality submissions.</p>
            <a href="{% url 'order:assignment'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="500">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-calendar4-week"></i>
            </div>
            <h3>Graphic Design</h3>
            <p>Creative graphic design solutions for your projects.</p>
            <a href="{% url 'order:graphics-design'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="600">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-chat-square-text"></i>
            </div>
            <h3>Transcription</h3>
            <p>Accurate transcription services for your audio and video files.</p>
            <a href="{% url 'order:transcription'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="700">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-play-circle"></i>
            </div>
            <h3>Video Editing</h3>
            <p>Professional video editing to enhance your multimedia projects.</p>
            <a href="{% url 'order:video-project'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div>
        <!-- End Service Item -->
         
        
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="800">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-code-slash"></i>
            </div>
            <h3>Web Development</h3>
            <p>Custom web development services to meet your specific needs.</p>
            <a href="{% url 'order:website-project'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="900">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-gear-fill"></i>
            </div>
            <h3>Programming Projects</h3>
            <p>Assistance with programming projects to help you succeed in your coursework.</p>
            <a href="{% url 'order:program-project'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div><!-- End Service Item -->
    
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="1000">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-pencil"></i>
            </div>
            <h3>Editing</h3>
            <p>Professional Editing services to polish your work.</p>
            <a href="{% url 'order:editing-project'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div>
        
        
        <!-- End Service Item -->
  
  
        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="1100">
          <div class="service-item position-relative">
            <div class="icon">
              <i class="bi bi-search"></i>
            </div>
            <h3>Research Assistance</h3>
            <p>Dedicated research assistance for your academic endeavors.</p>
            <a href="{%url 'order:research_help'%}" class="readmore stretched-link">Order Now <i class="bi bi-arrow-right"></i></a>
          </div>
        </div>
        
        <!-- End Service Item -->
    
      </div>
    
    </div>
    </section>

    {%endblock%}

ORDER/templates/order/writhing_editing.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}writhing-editing {% endblock %} </title>

{% block content %}
<div class="wrapper">
  <form method="post" action="{% url 'order:editing-project' %}" id="wizard" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- SECTION 1 -->
    <h2></h2>
    <section>
      <div class="inner">
        <div class="image-holder">
          <img src="{% static 'css/assets/img/form_images/istockphoto-1303500951-612x612.jpg' %}" alt="">
        </div>
        <div class="form-content">
          <div class="form-header">
            <h3>writhing-editing Submission Form</h3>
          </div>
          {% if messages %}
        <ul class="messages" id="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
          {% endif %}
          <p>Please fill with your details</p>
          <div class="form-row">
            <div class="form-holder">
              <input name="firstname" type="text" placeholder="First Name" class="form-control">
            </div>
            <div class="form-holder">
              <input name="lastname" type="text" placeholder="Last Name" class="form-control">
            </div>
          </div>
          <div class="form-row">
            <div class="form-holder">
              <input name="email" type="text" placeholder="Your Email" class="form-control">
            </div>
            <div class="form-holder">
              <input name="phone_number" type="text" placeholder="Phone Number" class="form-control">
            </div>
          </div>
          <div class="form-row">
            <div class="form-holder" style="align-self: flex-end; transform: translateY(4px);">
              <div class="checkbox-tick">
                <label class="male">
                  <input name="gender" type="radio" value="male" checked> Male<br>
                  <span class="checkmark"></span>
                </label>
                <label class="female">
                  <input type="radio" name="gender" value="female"> Female<br>
                  <span class="checkmark"></span>
                </label>
              </div>
            </div>
          </div>
          <div class="checkbox-circle">
            <label>
              <input type="checkbox" name="accept_terms" checked> Nor again is there anyone who loves or pursues or desires to obtaini.
              <span class="checkmark"></span>
            </label>
          </div>
        </div>
      </div>
    </section>

    <!-- SECTION 2 -->
    <h2></h2>
    <section>
      <div class="inner">
        <div class="image-holder">
          <img src="{% static 'css/assets/img/form_images/images.jpeg' %}" alt="">
        </div>
        <div class="form-content">
          <div class="form-header">
            <h3>writhing-editing Submission Form</h3>
          </div>
          <p>Please fill with project details</p>
 
          
          <div class="form-row">
          </div>
          <div class="form-row">
            <div class="form-holder">
              <input name="edited_file" type="file" placeholder="upload file" class="form-control">
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- SECTION 3 -->
    <h2></h2>
    <section>
      <div class="inner">
        <div class="image-holder">
          <img src="{% static 'css/assets/img/form_images/images (1).jpeg' %}" alt="">
        </div>
        <div class="form-content">
          <div class="form-header">
            <h3>writhing-editing Submission Form</h3>
          </div>
          <p>Send an optional message</p>
          <div class="form-row">
            <div class="form-holder w-100">
              <textarea name="description" placeholder="Your message here!" class="form-control" style="height: 99px;"></textarea>
            </div>
          </div>
          <div class="checkbox-circle mt-24">
            <label>
              <input type="checkbox" name="accept_terms" checked> Please accept <a href="{%url 'user:terms_and_conditions'%}">terms and conditions ?</a>
              <span class="checkmark"></span>
            </label>
          </div>
        </div>
      </div>
    </section>
  </form>
</div>


<!-- Template created and distributed by Colorlib -->
{% endblock %}